#!/usr/bin/env python

from __future__ import print_function

import argparse
import importlib
import sys

import rospy
import rostopic


SUBSCRIBE_MODE_HELP_TEXT = '''
You're interactively subscribed to a node. The first message is stored in in
the variable 'msg'.

To get more messages, call 'listen(num)', which waits for num messages to
arrive and then returns a list containing them.
'''.strip()


def subscribe_mode(topic, use_ipython):
    ''' Subscribe mode. REPL for receiving messages from a topic. '''

    def listen(num=1):
        ''' Request more messages from the topic. '''
        if num < 1:
            return None

        s = 's' if num > 1 else ''
        print('Waiting for message{} from {}...'.format(s, topic))

        msg_class, _, _ = rostopic.get_topic_class(topic)
        num_rec = 0
        msgs = []

        # Wait for the desired number of messages to come in.
        while num_rec < num:
            try:
                msg = rospy.wait_for_message(topic, msg_class)
                msgs.append(msg)
                num_rec += 1
            except rospy.ROSInterruptException:
                print('canceled.')
                return msgs

        print('done.')
        if num == 1:
            return msgs[0]
        else:
            return msgs

    def help():
        print(SUBSCRIBE_MODE_HELP_TEXT)

    msg = listen()

    try:
        import IPython
        IPython.embed(banner1='')
    except ImportError:
        import code
        print('\nCould not import IPython. Using standard interpreter.')
        code.interact(local=locals(), banner='')


def publish_mode(topic, use_ipython):
    ''' Publish mode. REPL for publishing to a topic. '''
    topic_class, _, _ = rostopic.get_topic_class(topic)
    publisher = rospy.Publisher(topic, topic_class, queue_size=1)

    # Import some common messages for the user's convenience.
    std = importlib.import_module('std_msgs.msg')
    geo = importlib.import_module('geometry_msgs.msg')
    sensor = importlib.import_module('sensor_msgs.msg')

    def publish(msg):
        ''' Convenient short-form for publisher.publish(msg). '''
        publisher.publish(msg)

    def help():
        print('Not yet implemented.')

    print('Publishing to {}...'.format(topic))

    try:
        import IPython
        IPython.embed(banner1='')
    except ImportError:
        import code
        print('\nCould not import IPython. Using standard interpreter.')
        code.interact(local=locals(), banner='')


def main():
    rospy.init_node('repl_node', anonymous=True)

    parser = argparse.ArgumentParser()
    parser.add_argument('topic', help='Name of the topic to interact with.')
    parser.add_argument('-p', '--publish', help='Publish mode.', action='store_true')
    parser.add_argument('-i', '--ipython', help='Use IPython REPL.', action='store_true')
    args = parser.parse_args()

    if args.publish:
        publish_mode(args.topic, args.ipython)
    else:
        subscribe_mode(args.topic, args.ipython)


if __name__ == '__main__':
    main()
